server.port: 8081
  #MySQL Database configuration
spring.datasource.url: jdbc:mysql://localhost:3306/mydb
spring.datasource.username: user
spring.datasource.password: secret


  #hibernate ddl auto (create , create-drop, validate, update)
spring.jpa.hibernate.ddl-auto: update

  #Display Application warn and errors and info
logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.Type: TRACE