server.port: 8081
  #MySQL Database configuration
spring.datasource.url: jdbc:mysql://localhost:3306/mydb
spring.datasource.username: user
spring.datasource.password: secret


  #hibernate ddl auto (create , create-drop, validate, update)
spring.jpa.hibernate.ddl-auto: update

  #Display Application warn and errors and info
logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.Type: TRACE

security.jwt.secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
# 1h in millisecond
security.jwt.expiration-time: 3600000